<?php

namespace AdamStipak\Webpay;

abstract class WebpayRequest
{

    protected array $params = [];

    /**
     * Set Digest for current request
     *
     * @param string $digest Verification signature of the string that is generated by concatenating all fields in the order given.
     * @internal
     */
    public function setDigest ($digest) {
        $this->params['DIGEST'] = $digest;
    }

    /**
     * Gives You all Request params
     * @return array
     */
    public function getParams (): array {
        return $this->params;
    }

    public function getSignParams (): array {
        $filterOutParams = ['LANG'];

        return array_filter($this->params, function (string $key) use ($filterOutParams) {
            return !in_array($key, $filterOutParams);
        }, ARRAY_FILTER_USE_KEY);
    }

    /**
     * Sets a value for a param key
     * @param string $key
     * @param $value
     */
    public function setParam ($key, $value) {
        $this->params[$key] = $value;
    }

    /**
     * Set The Merchant Number for request
     *
     * @param string $number Attributed merchant number.
     * @internal
     */
    public function setMerchantNumber ($number) {
        $this->params['MERCHANTNUMBER'] = $number;
    }

    /**
     * Add Description parameter to request fields
     *
     * @param string $value field value
     */
    public function setDescription ($value) {
        $this->params['DESCRIPTION'] = $value;
    }
}
